export const USERS_LOADING = "USERS_LOADING";
export const USERS_ERROR = "USERS_ERROR";
export const USERS_FETCH = "USERS_FETCH";
export const USERS_SORT_BY_DATE = "USERS_SORT_BY_DATE";
export const USER_UPDATE = "USER_UPDATE";